---
# Source: test-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: test-k8s-manifest
  labels:
    app: test-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: test-service
